# Generated by Django 5.2.8 on 2025-12-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_ingredient_is_available_alter_ingredient_unit"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE products_product DROP COLUMN IF EXISTS requires_bom;",
            reverse_sql="ALTER TABLE products_product ADD COLUMN requires_bom boolean NOT NULL DEFAULT false;",
        ),
    ]
