# Generated by Django 5.2.9 on 2026-01-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_requires_bom"),
        ("products", "0006_product_requires_bom"),
    ]

    operations = []
