# Generated by Django 5.2.8 on 2025-12-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE orders_order DROP COLUMN IF EXISTS is_archived;",
            reverse_sql="ALTER TABLE orders_order ADD COLUMN is_archived boolean NOT NULL DEFAULT false;",
        ),
    ]
