# Generated by Django 5.2.9 on 2026-01-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_is_archived"),
        ("orders", "0005_remove_order_is_archived"),
    ]

    operations = []
