# Generated by Django 5.2.8 on 2026-05-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the staff account was created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Flag indicating if the user account is soft-deleted or deactivated.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact details of the staff member.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CASHIER', 'Cashier')], default='CASHIER', help_text='Security authorization role designated to the staff member.', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the staff account was last modified.'),
        ),
    ]
