# Generated by Django 4.2.26 on 2025-11-05 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="Entity type (product, order, payment, user, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("ARCHIVE", "Archive"),
                            ("UNARCHIVE", "Unarchive"),
                            ("STOCK_ADJUST", "Stock Adjustment"),
                            ("PAYMENT_PROCESS", "Payment Processed"),
                            ("ORDER_STATUS", "Order Status Change"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                ("ref_id", models.IntegerField(help_text="ID of the affected record")),
                (
                    "diff",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Changes made (before/after values)",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full snapshot of record after action",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_trail",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity", "ref_id"],
                        name="audit_trail_entity_742207_idx",
                    ),
                    models.Index(
                        fields=["actor"], name="audit_trail_actor_i_7fad08_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_trail_action_5388db_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_trail_timesta_d857c8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="Entity type (product, order, user, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "ref_id",
                    models.IntegerField(help_text="Original ID of the archived record"),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Full JSON snapshot of the archived record"
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for archiving"
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who archived the record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "archives",
                "ordering": ["-archived_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "ref_id"], name="archives_entity_098e26_idx"
                    ),
                    models.Index(
                        fields=["archived_by"], name="archives_archive_c5e865_idx"
                    ),
                ],
            },
        ),
    ]
